version: '3.1'

services:
  mysql:
    container_name: mysql_local
    image: mysql:8.4
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d # 파일명 순서대로 실행
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=local_batch
      - MYSQL_USER=local_user
      - MYSQL_PASSWORD=local123
      - MYSQL_ROOT_PASSWORD=local123
      - TZ=Asia/Seoul